# Generated from the provider's pinned SQLite source fixture.
# Edit the generator inputs, then regenerate; do not edit this file by hand.

record "HumanResources_Department" {
  key = ["DepartmentID"]

  field "DepartmentID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "GroupName" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "HumanResources_Employee" {
  key = ["BusinessEntityID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_Person"
  }

  field "NationalIDNumber" {
    required = true
    type = "string"
  }

  field "LoginID" {
    required = true
    type = "string"
  }

  field "OrganizationNode" {
    type = "document"
  }

  field "OrganizationLevel" {
    type = "int"
  }

  field "JobTitle" {
    required = true
    type = "string"
  }

  field "BirthDate" {
    required = true
    type = "string"
  }

  field "MaritalStatus" {
    required = true
    type = "string"
  }

  field "Gender" {
    required = true
    type = "string"
  }

  field "HireDate" {
    required = true
    type = "string"
  }

  field "SalariedFlag" {
    required = true
    type = "int"
  }

  field "VacationHours" {
    required = true
    type = "int"
  }

  field "SickLeaveHours" {
    required = true
    type = "int"
  }

  field "CurrentFlag" {
    required = true
    type = "int"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "HumanResources_EmployeeDepartmentHistory" {
  key = ["BusinessEntityID","StartDate","DepartmentID","ShiftID"]

  field "BusinessEntityID" {
    required = true
    record = "HumanResources_Employee"
  }

  field "DepartmentID" {
    required = true
    record = "HumanResources_Department"
  }

  field "ShiftID" {
    required = true
    record = "HumanResources_Shift"
  }

  field "StartDate" {
    required = true
    type = "string"
  }

  field "EndDate" {
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "HumanResources_EmployeePayHistory" {
  key = ["BusinessEntityID","RateChangeDate"]

  field "BusinessEntityID" {
    required = true
    record = "HumanResources_Employee"
  }

  field "RateChangeDate" {
    required = true
    type = "string"
  }

  field "Rate" {
    required = true
    type = "decimal"
  }

  field "PayFrequency" {
    required = true
    type = "int"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "HumanResources_JobCandidate" {
  key = ["JobCandidateID"]

  field "JobCandidateID" {
    required = true
    type = "int"
  }

  field "BusinessEntityID" {
    record = "HumanResources_Employee"
  }

  field "Resume" {
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "HumanResources_Shift" {
  key = ["ShiftID"]

  field "ShiftID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "StartTime" {
    required = true
    type = "string"
  }

  field "EndTime" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_Address" {
  key = ["AddressID"]

  field "AddressID" {
    required = true
    type = "int"
  }

  field "AddressLine1" {
    required = true
    type = "string"
  }

  field "AddressLine2" {
    type = "string"
  }

  field "City" {
    required = true
    type = "string"
  }

  field "StateProvinceID" {
    required = true
    record = "Person_StateProvince"
  }

  field "PostalCode" {
    required = true
    type = "string"
  }

  field "SpatialLocation" {
    type = "document"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_AddressType" {
  key = ["AddressTypeID"]

  field "AddressTypeID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_BusinessEntity" {
  key = ["BusinessEntityID"]

  field "BusinessEntityID" {
    required = true
    type = "int"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_BusinessEntityAddress" {
  key = ["BusinessEntityID","AddressID","AddressTypeID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_BusinessEntity"
  }

  field "AddressID" {
    required = true
    record = "Person_Address"
  }

  field "AddressTypeID" {
    required = true
    record = "Person_AddressType"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_BusinessEntityContact" {
  key = ["BusinessEntityID","PersonID","ContactTypeID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_BusinessEntity"
  }

  field "PersonID" {
    required = true
    record = "Person_Person"
  }

  field "ContactTypeID" {
    required = true
    record = "Person_ContactType"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_ContactType" {
  key = ["ContactTypeID"]

  field "ContactTypeID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_CountryRegion" {
  key = ["CountryRegionCode"]

  field "CountryRegionCode" {
    required = true
    type = "string"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_EmailAddress" {
  key = ["BusinessEntityID","EmailAddressID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_Person"
  }

  field "EmailAddressID" {
    required = true
    type = "int"
  }

  field "EmailAddress" {
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_Password" {
  key = ["BusinessEntityID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_Person"
  }

  field "PasswordHash" {
    required = true
    type = "string"
  }

  field "PasswordSalt" {
    required = true
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_Person" {
  key = ["BusinessEntityID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_BusinessEntity"
  }

  field "PersonType" {
    required = true
    type = "string"
  }

  field "NameStyle" {
    required = true
    type = "int"
  }

  field "Title" {
    type = "string"
  }

  field "FirstName" {
    required = true
    type = "string"
  }

  field "MiddleName" {
    type = "string"
  }

  field "LastName" {
    required = true
    type = "string"
  }

  field "Suffix" {
    type = "string"
  }

  field "EmailPromotion" {
    required = true
    type = "int"
  }

  field "AdditionalContactInfo" {
    type = "string"
  }

  field "Demographics" {
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_PersonPhone" {
  key = ["BusinessEntityID","PhoneNumber","PhoneNumberTypeID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_Person"
  }

  field "PhoneNumber" {
    required = true
    type = "string"
  }

  field "PhoneNumberTypeID" {
    required = true
    record = "Person_PhoneNumberType"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_PhoneNumberType" {
  key = ["PhoneNumberTypeID"]

  field "PhoneNumberTypeID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Person_StateProvince" {
  key = ["StateProvinceID"]

  field "StateProvinceID" {
    required = true
    type = "int"
  }

  field "StateProvinceCode" {
    required = true
    type = "string"
  }

  field "CountryRegionCode" {
    required = true
    record = "Person_CountryRegion"
  }

  field "IsOnlyStateProvinceFlag" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "TerritoryID" {
    required = true
    record = "Sales_SalesTerritory"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_BillOfMaterials" {
  key = ["BillOfMaterialsID"]

  field "BillOfMaterialsID" {
    required = true
    type = "int"
  }

  field "ProductAssemblyID" {
    record = "Production_Product"
  }

  field "ComponentID" {
    required = true
    record = "Production_Product"
  }

  field "StartDate" {
    required = true
    type = "string"
  }

  field "EndDate" {
    type = "string"
  }

  field "UnitMeasureCode" {
    required = true
    record = "Production_UnitMeasure"
  }

  field "BOMLevel" {
    required = true
    type = "int"
  }

  field "PerAssemblyQty" {
    required = true
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_Culture" {
  key = ["CultureID"]

  field "CultureID" {
    required = true
    type = "string"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_Document" {
  key = ["DocumentNode"]

  field "DocumentNode" {
    required = true
    type = "document"
  }

  field "DocumentLevel" {
    type = "int"
  }

  field "Title" {
    required = true
    type = "string"
  }

  field "Owner" {
    required = true
    record = "HumanResources_Employee"
  }

  field "FolderFlag" {
    required = true
    type = "int"
  }

  field "FileName" {
    required = true
    type = "string"
  }

  field "FileExtension" {
    required = true
    type = "string"
  }

  field "Revision" {
    required = true
    type = "string"
  }

  field "ChangeNumber" {
    required = true
    type = "int"
  }

  field "Status" {
    required = true
    type = "int"
  }

  field "DocumentSummary" {
    type = "string"
  }

  field "Document" {
    type = "document"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_Illustration" {
  key = ["IllustrationID"]

  field "IllustrationID" {
    required = true
    type = "int"
  }

  field "Diagram" {
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_Location" {
  key = ["LocationID"]

  field "LocationID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "CostRate" {
    required = true
    type = "decimal"
  }

  field "Availability" {
    required = true
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_Product" {
  key = ["ProductID"]

  field "ProductID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ProductNumber" {
    required = true
    type = "string"
  }

  field "MakeFlag" {
    required = true
    type = "int"
  }

  field "FinishedGoodsFlag" {
    required = true
    type = "int"
  }

  field "Color" {
    type = "string"
  }

  field "SafetyStockLevel" {
    required = true
    type = "int"
  }

  field "ReorderPoint" {
    required = true
    type = "int"
  }

  field "StandardCost" {
    required = true
    type = "decimal"
  }

  field "ListPrice" {
    required = true
    type = "decimal"
  }

  field "Size" {
    type = "string"
  }

  field "SizeUnitMeasureCode" {
    record = "Production_UnitMeasure"
  }

  field "WeightUnitMeasureCode" {
    record = "Production_UnitMeasure"
  }

  field "Weight" {
    type = "decimal"
  }

  field "DaysToManufacture" {
    required = true
    type = "int"
  }

  field "ProductLine" {
    type = "string"
  }

  field "Class" {
    type = "string"
  }

  field "Style" {
    type = "string"
  }

  field "ProductSubcategoryID" {
    record = "Production_ProductSubcategory"
  }

  field "ProductModelID" {
    record = "Production_ProductModel"
  }

  field "SellStartDate" {
    required = true
    type = "string"
  }

  field "SellEndDate" {
    type = "string"
  }

  field "DiscontinuedDate" {
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductCategory" {
  key = ["ProductCategoryID"]

  field "ProductCategoryID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductCostHistory" {
  key = ["ProductID","StartDate"]

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "StartDate" {
    required = true
    type = "string"
  }

  field "EndDate" {
    type = "string"
  }

  field "StandardCost" {
    required = true
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductDescription" {
  key = ["ProductDescriptionID"]

  field "ProductDescriptionID" {
    required = true
    type = "int"
  }

  field "Description" {
    required = true
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductDocument" {
  key = ["ProductID","DocumentNode"]

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "DocumentNode" {
    required = true
    record = "Production_Document"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductInventory" {
  key = ["ProductID","LocationID"]

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "LocationID" {
    required = true
    record = "Production_Location"
  }

  field "Shelf" {
    required = true
    type = "string"
  }

  field "Bin" {
    required = true
    type = "int"
  }

  field "Quantity" {
    required = true
    type = "int"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductListPriceHistory" {
  key = ["ProductID","StartDate"]

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "StartDate" {
    required = true
    type = "string"
  }

  field "EndDate" {
    type = "string"
  }

  field "ListPrice" {
    required = true
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductModel" {
  key = ["ProductModelID"]

  field "ProductModelID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "CatalogDescription" {
    type = "string"
  }

  field "Instructions" {
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductModelIllustration" {
  key = ["ProductModelID","IllustrationID"]

  field "ProductModelID" {
    required = true
    record = "Production_ProductModel"
  }

  field "IllustrationID" {
    required = true
    record = "Production_Illustration"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductModelProductDescriptionCulture" {
  key = ["ProductModelID","ProductDescriptionID","CultureID"]

  field "ProductModelID" {
    required = true
    record = "Production_ProductModel"
  }

  field "ProductDescriptionID" {
    required = true
    record = "Production_ProductDescription"
  }

  field "CultureID" {
    required = true
    record = "Production_Culture"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductPhoto" {
  key = ["ProductPhotoID"]

  field "ProductPhotoID" {
    required = true
    type = "int"
  }

  field "ThumbNailPhoto" {
    type = "document"
  }

  field "ThumbnailPhotoFileName" {
    type = "string"
  }

  field "LargePhoto" {
    type = "document"
  }

  field "LargePhotoFileName" {
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductProductPhoto" {
  key = ["ProductID","ProductPhotoID"]

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "ProductPhotoID" {
    required = true
    record = "Production_ProductPhoto"
  }

  field "Primary" {
    required = true
    type = "int"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductReview" {
  key = ["ProductReviewID"]

  field "ProductReviewID" {
    required = true
    type = "int"
  }

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "ReviewerName" {
    required = true
    type = "string"
  }

  field "ReviewDate" {
    required = true
    type = "string"
  }

  field "EmailAddress" {
    required = true
    type = "string"
  }

  field "Rating" {
    required = true
    type = "int"
  }

  field "Comments" {
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ProductSubcategory" {
  key = ["ProductSubcategoryID"]

  field "ProductSubcategoryID" {
    required = true
    type = "int"
  }

  field "ProductCategoryID" {
    required = true
    record = "Production_ProductCategory"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_ScrapReason" {
  key = ["ScrapReasonID"]

  field "ScrapReasonID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_TransactionHistory" {
  key = ["TransactionID"]

  field "TransactionID" {
    required = true
    type = "int"
  }

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "ReferenceOrderID" {
    required = true
    type = "int"
  }

  field "ReferenceOrderLineID" {
    required = true
    type = "int"
  }

  field "TransactionDate" {
    required = true
    type = "string"
  }

  field "TransactionType" {
    required = true
    type = "string"
  }

  field "Quantity" {
    required = true
    type = "int"
  }

  field "ActualCost" {
    required = true
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_TransactionHistoryArchive" {
  key = ["TransactionID"]

  field "TransactionID" {
    required = true
    type = "int"
  }

  field "ProductID" {
    required = true
    type = "int"
  }

  field "ReferenceOrderID" {
    required = true
    type = "int"
  }

  field "ReferenceOrderLineID" {
    required = true
    type = "int"
  }

  field "TransactionDate" {
    required = true
    type = "string"
  }

  field "TransactionType" {
    required = true
    type = "string"
  }

  field "Quantity" {
    required = true
    type = "int"
  }

  field "ActualCost" {
    required = true
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_UnitMeasure" {
  key = ["UnitMeasureCode"]

  field "UnitMeasureCode" {
    required = true
    type = "string"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_WorkOrder" {
  key = ["WorkOrderID"]

  field "WorkOrderID" {
    required = true
    type = "int"
  }

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "OrderQty" {
    required = true
    type = "int"
  }

  field "StockedQty" {
    type = "decimal"
  }

  field "ScrappedQty" {
    required = true
    type = "int"
  }

  field "StartDate" {
    required = true
    type = "string"
  }

  field "EndDate" {
    type = "string"
  }

  field "DueDate" {
    required = true
    type = "string"
  }

  field "ScrapReasonID" {
    record = "Production_ScrapReason"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Production_WorkOrderRouting" {
  key = ["WorkOrderID","ProductID","OperationSequence"]

  field "WorkOrderID" {
    required = true
    record = "Production_WorkOrder"
  }

  field "ProductID" {
    required = true
    type = "int"
  }

  field "OperationSequence" {
    required = true
    type = "int"
  }

  field "LocationID" {
    required = true
    record = "Production_Location"
  }

  field "ScheduledStartDate" {
    required = true
    type = "string"
  }

  field "ScheduledEndDate" {
    required = true
    type = "string"
  }

  field "ActualStartDate" {
    type = "string"
  }

  field "ActualEndDate" {
    type = "string"
  }

  field "ActualResourceHrs" {
    type = "decimal"
  }

  field "PlannedCost" {
    required = true
    type = "decimal"
  }

  field "ActualCost" {
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Purchasing_ProductVendor" {
  key = ["ProductID","BusinessEntityID"]

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "BusinessEntityID" {
    required = true
    record = "Purchasing_Vendor"
  }

  field "AverageLeadTime" {
    required = true
    type = "int"
  }

  field "StandardPrice" {
    required = true
    type = "decimal"
  }

  field "LastReceiptCost" {
    type = "decimal"
  }

  field "LastReceiptDate" {
    type = "string"
  }

  field "MinOrderQty" {
    required = true
    type = "int"
  }

  field "MaxOrderQty" {
    required = true
    type = "int"
  }

  field "OnOrderQty" {
    type = "int"
  }

  field "UnitMeasureCode" {
    required = true
    record = "Production_UnitMeasure"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Purchasing_PurchaseOrderDetail" {
  key = ["PurchaseOrderID","PurchaseOrderDetailID"]

  field "PurchaseOrderID" {
    required = true
    record = "Purchasing_PurchaseOrderHeader"
  }

  field "PurchaseOrderDetailID" {
    required = true
    type = "int"
  }

  field "DueDate" {
    required = true
    type = "string"
  }

  field "OrderQty" {
    required = true
    type = "int"
  }

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "UnitPrice" {
    required = true
    type = "decimal"
  }

  field "LineTotal" {
    type = "decimal"
  }

  field "ReceivedQty" {
    required = true
    type = "decimal"
  }

  field "RejectedQty" {
    required = true
    type = "decimal"
  }

  field "StockedQty" {
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Purchasing_PurchaseOrderHeader" {
  key = ["PurchaseOrderID"]

  field "PurchaseOrderID" {
    required = true
    type = "int"
  }

  field "RevisionNumber" {
    required = true
    type = "int"
  }

  field "Status" {
    required = true
    type = "int"
  }

  field "EmployeeID" {
    required = true
    record = "HumanResources_Employee"
  }

  field "VendorID" {
    required = true
    record = "Purchasing_Vendor"
  }

  field "ShipMethodID" {
    required = true
    record = "Purchasing_ShipMethod"
  }

  field "OrderDate" {
    required = true
    type = "string"
  }

  field "ShipDate" {
    type = "string"
  }

  field "SubTotal" {
    required = true
    type = "decimal"
  }

  field "TaxAmt" {
    required = true
    type = "decimal"
  }

  field "Freight" {
    required = true
    type = "decimal"
  }

  field "TotalDue" {
    required = true
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Purchasing_ShipMethod" {
  key = ["ShipMethodID"]

  field "ShipMethodID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ShipBase" {
    required = true
    type = "decimal"
  }

  field "ShipRate" {
    required = true
    type = "decimal"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Purchasing_Vendor" {
  key = ["BusinessEntityID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_BusinessEntity"
  }

  field "AccountNumber" {
    required = true
    type = "string"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "CreditRating" {
    required = true
    type = "int"
  }

  field "PreferredVendorStatus" {
    required = true
    type = "int"
  }

  field "ActiveFlag" {
    required = true
    type = "int"
  }

  field "PurchasingWebServiceURL" {
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_CountryRegionCurrency" {
  key = ["CountryRegionCode","CurrencyCode"]

  field "CountryRegionCode" {
    required = true
    record = "Person_CountryRegion"
  }

  field "CurrencyCode" {
    required = true
    record = "Sales_Currency"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_CreditCard" {
  key = ["CreditCardID"]

  field "CreditCardID" {
    required = true
    type = "int"
  }

  field "CardType" {
    required = true
    type = "string"
  }

  field "CardNumber" {
    required = true
    type = "string"
  }

  field "ExpMonth" {
    required = true
    type = "int"
  }

  field "ExpYear" {
    required = true
    type = "int"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_Currency" {
  key = ["CurrencyCode"]

  field "CurrencyCode" {
    required = true
    type = "string"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_CurrencyRate" {
  key = ["CurrencyRateID"]

  field "CurrencyRateID" {
    required = true
    type = "int"
  }

  field "CurrencyRateDate" {
    required = true
    type = "string"
  }

  field "FromCurrencyCode" {
    required = true
    record = "Sales_Currency"
  }

  field "ToCurrencyCode" {
    required = true
    record = "Sales_Currency"
  }

  field "AverageRate" {
    required = true
    type = "decimal"
  }

  field "EndOfDayRate" {
    required = true
    type = "decimal"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_Customer" {
  key = ["CustomerID"]

  field "CustomerID" {
    required = true
    type = "int"
  }

  field "PersonID" {
    record = "Person_Person"
  }

  field "StoreID" {
    record = "Sales_Store"
  }

  field "TerritoryID" {
    record = "Sales_SalesTerritory"
  }

  field "AccountNumber" {
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_PersonCreditCard" {
  key = ["BusinessEntityID","CreditCardID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_Person"
  }

  field "CreditCardID" {
    required = true
    record = "Sales_CreditCard"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesOrderDetail" {
  key = ["SalesOrderID","SalesOrderDetailID"]

  field "SalesOrderID" {
    required = true
    record = "Sales_SalesOrderHeader"
  }

  field "SalesOrderDetailID" {
    required = true
    type = "int"
  }

  field "CarrierTrackingNumber" {
    type = "string"
  }

  field "OrderQty" {
    required = true
    type = "int"
  }

  field "ProductID" {
    required = true
    record = "Sales_SpecialOfferProduct"
  }

  field "SpecialOfferID" {
    required = true
    record = "Sales_SpecialOfferProduct"
  }

  field "UnitPrice" {
    required = true
    type = "decimal"
  }

  field "UnitPriceDiscount" {
    required = true
    type = "decimal"
  }

  field "LineTotal" {
    type = "decimal"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesOrderHeader" {
  key = ["SalesOrderID"]

  field "SalesOrderID" {
    required = true
    type = "int"
  }

  field "RevisionNumber" {
    required = true
    type = "int"
  }

  field "OrderDate" {
    required = true
    type = "string"
  }

  field "DueDate" {
    required = true
    type = "string"
  }

  field "ShipDate" {
    type = "string"
  }

  field "Status" {
    required = true
    type = "int"
  }

  field "OnlineOrderFlag" {
    required = true
    type = "int"
  }

  field "SalesOrderNumber" {
    type = "string"
  }

  field "PurchaseOrderNumber" {
    type = "string"
  }

  field "AccountNumber" {
    type = "string"
  }

  field "CustomerID" {
    required = true
    record = "Sales_Customer"
  }

  field "SalesPersonID" {
    record = "Sales_SalesPerson"
  }

  field "TerritoryID" {
    record = "Sales_SalesTerritory"
  }

  field "BillToAddressID" {
    required = true
    record = "Person_Address"
  }

  field "ShipToAddressID" {
    required = true
    record = "Person_Address"
  }

  field "ShipMethodID" {
    required = true
    record = "Purchasing_ShipMethod"
  }

  field "CreditCardID" {
    record = "Sales_CreditCard"
  }

  field "CreditCardApprovalCode" {
    type = "string"
  }

  field "CurrencyRateID" {
    record = "Sales_CurrencyRate"
  }

  field "SubTotal" {
    required = true
    type = "decimal"
  }

  field "TaxAmt" {
    required = true
    type = "decimal"
  }

  field "Freight" {
    required = true
    type = "decimal"
  }

  field "TotalDue" {
    type = "decimal"
  }

  field "Comment" {
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesOrderHeaderSalesReason" {
  key = ["SalesOrderID","SalesReasonID"]

  field "SalesOrderID" {
    required = true
    record = "Sales_SalesOrderHeader"
  }

  field "SalesReasonID" {
    required = true
    record = "Sales_SalesReason"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesPerson" {
  key = ["BusinessEntityID"]

  field "BusinessEntityID" {
    required = true
    record = "HumanResources_Employee"
  }

  field "TerritoryID" {
    record = "Sales_SalesTerritory"
  }

  field "SalesQuota" {
    type = "decimal"
  }

  field "Bonus" {
    required = true
    type = "decimal"
  }

  field "CommissionPct" {
    required = true
    type = "decimal"
  }

  field "SalesYTD" {
    required = true
    type = "decimal"
  }

  field "SalesLastYear" {
    required = true
    type = "decimal"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesPersonQuotaHistory" {
  key = ["BusinessEntityID","QuotaDate"]

  field "BusinessEntityID" {
    required = true
    record = "Sales_SalesPerson"
  }

  field "QuotaDate" {
    required = true
    type = "string"
  }

  field "SalesQuota" {
    required = true
    type = "decimal"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesReason" {
  key = ["SalesReasonID"]

  field "SalesReasonID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "ReasonType" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesTaxRate" {
  key = ["SalesTaxRateID"]

  field "SalesTaxRateID" {
    required = true
    type = "int"
  }

  field "StateProvinceID" {
    required = true
    record = "Person_StateProvince"
  }

  field "TaxType" {
    required = true
    type = "int"
  }

  field "TaxRate" {
    required = true
    type = "decimal"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesTerritory" {
  key = ["TerritoryID"]

  field "TerritoryID" {
    required = true
    type = "int"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "CountryRegionCode" {
    required = true
    record = "Person_CountryRegion"
  }

  field "Group" {
    required = true
    type = "string"
  }

  field "SalesYTD" {
    required = true
    type = "decimal"
  }

  field "SalesLastYear" {
    required = true
    type = "decimal"
  }

  field "CostYTD" {
    required = true
    type = "decimal"
  }

  field "CostLastYear" {
    required = true
    type = "decimal"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SalesTerritoryHistory" {
  key = ["BusinessEntityID","StartDate","TerritoryID"]

  field "BusinessEntityID" {
    required = true
    record = "Sales_SalesPerson"
  }

  field "TerritoryID" {
    required = true
    record = "Sales_SalesTerritory"
  }

  field "StartDate" {
    required = true
    type = "string"
  }

  field "EndDate" {
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_ShoppingCartItem" {
  key = ["ShoppingCartItemID"]

  field "ShoppingCartItemID" {
    required = true
    type = "int"
  }

  field "ShoppingCartID" {
    required = true
    type = "string"
  }

  field "Quantity" {
    required = true
    type = "int"
  }

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "DateCreated" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SpecialOffer" {
  key = ["SpecialOfferID"]

  field "SpecialOfferID" {
    required = true
    type = "int"
  }

  field "Description" {
    required = true
    type = "string"
  }

  field "DiscountPct" {
    required = true
    type = "decimal"
  }

  field "Type" {
    required = true
    type = "string"
  }

  field "Category" {
    required = true
    type = "string"
  }

  field "StartDate" {
    required = true
    type = "string"
  }

  field "EndDate" {
    required = true
    type = "string"
  }

  field "MinQty" {
    required = true
    type = "int"
  }

  field "MaxQty" {
    type = "int"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_SpecialOfferProduct" {
  key = ["SpecialOfferID","ProductID"]

  field "SpecialOfferID" {
    required = true
    record = "Sales_SpecialOffer"
  }

  field "ProductID" {
    required = true
    record = "Production_Product"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "Sales_Store" {
  key = ["BusinessEntityID"]

  field "BusinessEntityID" {
    required = true
    record = "Person_BusinessEntity"
  }

  field "Name" {
    required = true
    type = "string"
  }

  field "SalesPersonID" {
    record = "Sales_SalesPerson"
  }

  field "Demographics" {
    type = "string"
  }

  field "rowguid" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "dbo_AWBuildVersion" {
  key = ["SystemInformationID"]

  field "SystemInformationID" {
    required = true
    type = "int"
  }

  field "Database_Version" {
    required = true
    type = "string"
  }

  field "VersionDate" {
    required = true
    type = "string"
  }

  field "ModifiedDate" {
    required = true
    type = "string"
  }
}

record "dbo_DatabaseLog" {
  key = ["DatabaseLogID"]

  field "DatabaseLogID" {
    required = true
    type = "int"
  }

  field "PostTime" {
    required = true
    type = "string"
  }

  field "DatabaseUser" {
    required = true
    type = "string"
  }

  field "Event" {
    required = true
    type = "string"
  }

  field "Schema" {
    type = "string"
  }

  field "Object" {
    type = "string"
  }

  field "TSQL" {
    required = true
    type = "string"
  }

  field "XmlEvent" {
    required = true
    type = "string"
  }
}

record "dbo_ErrorLog" {
  key = ["ErrorLogID"]

  field "ErrorLogID" {
    required = true
    type = "int"
  }

  field "ErrorTime" {
    required = true
    type = "string"
  }

  field "UserName" {
    required = true
    type = "string"
  }

  field "ErrorNumber" {
    required = true
    type = "int"
  }

  field "ErrorSeverity" {
    type = "int"
  }

  field "ErrorState" {
    type = "int"
  }

  field "ErrorProcedure" {
    type = "string"
  }

  field "ErrorLine" {
    type = "int"
  }

  field "ErrorMessage" {
    required = true
    type = "string"
  }
}
