# Generated from the provider's pinned SQLite source fixture.
# Edit the generator inputs, then regenerate; do not edit this file by hand.

entity "HumanResources_Department" {
  key = ["DepartmentID"]

  property "DepartmentID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "GroupName" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "HumanResources_Employee" {
  key = ["BusinessEntityID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_Person"
  }

  property "NationalIDNumber" {
    required = true
    type = "string"
  }

  property "LoginID" {
    required = true
    type = "string"
  }

  property "OrganizationNode" {
    type = "document"
  }

  property "OrganizationLevel" {
    type = "int"
  }

  property "JobTitle" {
    required = true
    type = "string"
  }

  property "BirthDate" {
    required = true
    type = "string"
  }

  property "MaritalStatus" {
    required = true
    type = "string"
  }

  property "Gender" {
    required = true
    type = "string"
  }

  property "HireDate" {
    required = true
    type = "string"
  }

  property "SalariedFlag" {
    required = true
    type = "int"
  }

  property "VacationHours" {
    required = true
    type = "int"
  }

  property "SickLeaveHours" {
    required = true
    type = "int"
  }

  property "CurrentFlag" {
    required = true
    type = "int"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "HumanResources_EmployeeDepartmentHistory" {
  key = ["BusinessEntityID","StartDate","DepartmentID","ShiftID"]

  property "BusinessEntityID" {
    required = true
    entity = "HumanResources_Employee"
  }

  property "DepartmentID" {
    required = true
    entity = "HumanResources_Department"
  }

  property "ShiftID" {
    required = true
    entity = "HumanResources_Shift"
  }

  property "StartDate" {
    required = true
    type = "string"
  }

  property "EndDate" {
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "HumanResources_EmployeePayHistory" {
  key = ["BusinessEntityID","RateChangeDate"]

  property "BusinessEntityID" {
    required = true
    entity = "HumanResources_Employee"
  }

  property "RateChangeDate" {
    required = true
    type = "string"
  }

  property "Rate" {
    required = true
    type = "decimal"
  }

  property "PayFrequency" {
    required = true
    type = "int"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "HumanResources_JobCandidate" {
  key = ["JobCandidateID"]

  property "JobCandidateID" {
    required = true
    type = "int"
  }

  property "BusinessEntityID" {
    entity = "HumanResources_Employee"
  }

  property "Resume" {
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "HumanResources_Shift" {
  key = ["ShiftID"]

  property "ShiftID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "StartTime" {
    required = true
    type = "string"
  }

  property "EndTime" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_Address" {
  key = ["AddressID"]

  property "AddressID" {
    required = true
    type = "int"
  }

  property "AddressLine1" {
    required = true
    type = "string"
  }

  property "AddressLine2" {
    type = "string"
  }

  property "City" {
    required = true
    type = "string"
  }

  property "StateProvinceID" {
    required = true
    entity = "Person_StateProvince"
  }

  property "PostalCode" {
    required = true
    type = "string"
  }

  property "SpatialLocation" {
    type = "document"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_AddressType" {
  key = ["AddressTypeID"]

  property "AddressTypeID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_BusinessEntity" {
  key = ["BusinessEntityID"]

  property "BusinessEntityID" {
    required = true
    type = "int"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_BusinessEntityAddress" {
  key = ["BusinessEntityID","AddressID","AddressTypeID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_BusinessEntity"
  }

  property "AddressID" {
    required = true
    entity = "Person_Address"
  }

  property "AddressTypeID" {
    required = true
    entity = "Person_AddressType"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_BusinessEntityContact" {
  key = ["BusinessEntityID","PersonID","ContactTypeID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_BusinessEntity"
  }

  property "PersonID" {
    required = true
    entity = "Person_Person"
  }

  property "ContactTypeID" {
    required = true
    entity = "Person_ContactType"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_ContactType" {
  key = ["ContactTypeID"]

  property "ContactTypeID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_CountryRegion" {
  key = ["CountryRegionCode"]

  property "CountryRegionCode" {
    required = true
    type = "string"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_EmailAddress" {
  key = ["BusinessEntityID","EmailAddressID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_Person"
  }

  property "EmailAddressID" {
    required = true
    type = "int"
  }

  property "EmailAddress" {
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_Password" {
  key = ["BusinessEntityID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_Person"
  }

  property "PasswordHash" {
    required = true
    type = "string"
  }

  property "PasswordSalt" {
    required = true
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_Person" {
  key = ["BusinessEntityID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_BusinessEntity"
  }

  property "PersonType" {
    required = true
    type = "string"
  }

  property "NameStyle" {
    required = true
    type = "int"
  }

  property "Title" {
    type = "string"
  }

  property "FirstName" {
    required = true
    type = "string"
  }

  property "MiddleName" {
    type = "string"
  }

  property "LastName" {
    required = true
    type = "string"
  }

  property "Suffix" {
    type = "string"
  }

  property "EmailPromotion" {
    required = true
    type = "int"
  }

  property "AdditionalContactInfo" {
    type = "string"
  }

  property "Demographics" {
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_PersonPhone" {
  key = ["BusinessEntityID","PhoneNumber","PhoneNumberTypeID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_Person"
  }

  property "PhoneNumber" {
    required = true
    type = "string"
  }

  property "PhoneNumberTypeID" {
    required = true
    entity = "Person_PhoneNumberType"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_PhoneNumberType" {
  key = ["PhoneNumberTypeID"]

  property "PhoneNumberTypeID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Person_StateProvince" {
  key = ["StateProvinceID"]

  property "StateProvinceID" {
    required = true
    type = "int"
  }

  property "StateProvinceCode" {
    required = true
    type = "string"
  }

  property "CountryRegionCode" {
    required = true
    entity = "Person_CountryRegion"
  }

  property "IsOnlyStateProvinceFlag" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "TerritoryID" {
    required = true
    entity = "Sales_SalesTerritory"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_BillOfMaterials" {
  key = ["BillOfMaterialsID"]

  property "BillOfMaterialsID" {
    required = true
    type = "int"
  }

  property "ProductAssemblyID" {
    entity = "Production_Product"
  }

  property "ComponentID" {
    required = true
    entity = "Production_Product"
  }

  property "StartDate" {
    required = true
    type = "string"
  }

  property "EndDate" {
    type = "string"
  }

  property "UnitMeasureCode" {
    required = true
    entity = "Production_UnitMeasure"
  }

  property "BOMLevel" {
    required = true
    type = "int"
  }

  property "PerAssemblyQty" {
    required = true
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_Culture" {
  key = ["CultureID"]

  property "CultureID" {
    required = true
    type = "string"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_Document" {
  key = ["DocumentNode"]

  property "DocumentNode" {
    required = true
    type = "document"
  }

  property "DocumentLevel" {
    type = "int"
  }

  property "Title" {
    required = true
    type = "string"
  }

  property "Owner" {
    required = true
    entity = "HumanResources_Employee"
  }

  property "FolderFlag" {
    required = true
    type = "int"
  }

  property "FileName" {
    required = true
    type = "string"
  }

  property "FileExtension" {
    required = true
    type = "string"
  }

  property "Revision" {
    required = true
    type = "string"
  }

  property "ChangeNumber" {
    required = true
    type = "int"
  }

  property "Status" {
    required = true
    type = "int"
  }

  property "DocumentSummary" {
    type = "string"
  }

  property "Document" {
    type = "document"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_Illustration" {
  key = ["IllustrationID"]

  property "IllustrationID" {
    required = true
    type = "int"
  }

  property "Diagram" {
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_Location" {
  key = ["LocationID"]

  property "LocationID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "CostRate" {
    required = true
    type = "decimal"
  }

  property "Availability" {
    required = true
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_Product" {
  key = ["ProductID"]

  property "ProductID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ProductNumber" {
    required = true
    type = "string"
  }

  property "MakeFlag" {
    required = true
    type = "int"
  }

  property "FinishedGoodsFlag" {
    required = true
    type = "int"
  }

  property "Color" {
    type = "string"
  }

  property "SafetyStockLevel" {
    required = true
    type = "int"
  }

  property "ReorderPoint" {
    required = true
    type = "int"
  }

  property "StandardCost" {
    required = true
    type = "decimal"
  }

  property "ListPrice" {
    required = true
    type = "decimal"
  }

  property "Size" {
    type = "string"
  }

  property "SizeUnitMeasureCode" {
    entity = "Production_UnitMeasure"
  }

  property "WeightUnitMeasureCode" {
    entity = "Production_UnitMeasure"
  }

  property "Weight" {
    type = "decimal"
  }

  property "DaysToManufacture" {
    required = true
    type = "int"
  }

  property "ProductLine" {
    type = "string"
  }

  property "Class" {
    type = "string"
  }

  property "Style" {
    type = "string"
  }

  property "ProductSubcategoryID" {
    entity = "Production_ProductSubcategory"
  }

  property "ProductModelID" {
    entity = "Production_ProductModel"
  }

  property "SellStartDate" {
    required = true
    type = "string"
  }

  property "SellEndDate" {
    type = "string"
  }

  property "DiscontinuedDate" {
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductCategory" {
  key = ["ProductCategoryID"]

  property "ProductCategoryID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductCostHistory" {
  key = ["ProductID","StartDate"]

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "StartDate" {
    required = true
    type = "string"
  }

  property "EndDate" {
    type = "string"
  }

  property "StandardCost" {
    required = true
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductDescription" {
  key = ["ProductDescriptionID"]

  property "ProductDescriptionID" {
    required = true
    type = "int"
  }

  property "Description" {
    required = true
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductDocument" {
  key = ["ProductID","DocumentNode"]

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "DocumentNode" {
    required = true
    entity = "Production_Document"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductInventory" {
  key = ["ProductID","LocationID"]

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "LocationID" {
    required = true
    entity = "Production_Location"
  }

  property "Shelf" {
    required = true
    type = "string"
  }

  property "Bin" {
    required = true
    type = "int"
  }

  property "Quantity" {
    required = true
    type = "int"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductListPriceHistory" {
  key = ["ProductID","StartDate"]

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "StartDate" {
    required = true
    type = "string"
  }

  property "EndDate" {
    type = "string"
  }

  property "ListPrice" {
    required = true
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductModel" {
  key = ["ProductModelID"]

  property "ProductModelID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "CatalogDescription" {
    type = "string"
  }

  property "Instructions" {
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductModelIllustration" {
  key = ["ProductModelID","IllustrationID"]

  property "ProductModelID" {
    required = true
    entity = "Production_ProductModel"
  }

  property "IllustrationID" {
    required = true
    entity = "Production_Illustration"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductModelProductDescriptionCulture" {
  key = ["ProductModelID","ProductDescriptionID","CultureID"]

  property "ProductModelID" {
    required = true
    entity = "Production_ProductModel"
  }

  property "ProductDescriptionID" {
    required = true
    entity = "Production_ProductDescription"
  }

  property "CultureID" {
    required = true
    entity = "Production_Culture"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductPhoto" {
  key = ["ProductPhotoID"]

  property "ProductPhotoID" {
    required = true
    type = "int"
  }

  property "ThumbNailPhoto" {
    type = "document"
  }

  property "ThumbnailPhotoFileName" {
    type = "string"
  }

  property "LargePhoto" {
    type = "document"
  }

  property "LargePhotoFileName" {
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductProductPhoto" {
  key = ["ProductID","ProductPhotoID"]

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "ProductPhotoID" {
    required = true
    entity = "Production_ProductPhoto"
  }

  property "Primary" {
    required = true
    type = "int"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductReview" {
  key = ["ProductReviewID"]

  property "ProductReviewID" {
    required = true
    type = "int"
  }

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "ReviewerName" {
    required = true
    type = "string"
  }

  property "ReviewDate" {
    required = true
    type = "string"
  }

  property "EmailAddress" {
    required = true
    type = "string"
  }

  property "Rating" {
    required = true
    type = "int"
  }

  property "Comments" {
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ProductSubcategory" {
  key = ["ProductSubcategoryID"]

  property "ProductSubcategoryID" {
    required = true
    type = "int"
  }

  property "ProductCategoryID" {
    required = true
    entity = "Production_ProductCategory"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_ScrapReason" {
  key = ["ScrapReasonID"]

  property "ScrapReasonID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_TransactionHistory" {
  key = ["TransactionID"]

  property "TransactionID" {
    required = true
    type = "int"
  }

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "ReferenceOrderID" {
    required = true
    type = "int"
  }

  property "ReferenceOrderLineID" {
    required = true
    type = "int"
  }

  property "TransactionDate" {
    required = true
    type = "string"
  }

  property "TransactionType" {
    required = true
    type = "string"
  }

  property "Quantity" {
    required = true
    type = "int"
  }

  property "ActualCost" {
    required = true
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_TransactionHistoryArchive" {
  key = ["TransactionID"]

  property "TransactionID" {
    required = true
    type = "int"
  }

  property "ProductID" {
    required = true
    type = "int"
  }

  property "ReferenceOrderID" {
    required = true
    type = "int"
  }

  property "ReferenceOrderLineID" {
    required = true
    type = "int"
  }

  property "TransactionDate" {
    required = true
    type = "string"
  }

  property "TransactionType" {
    required = true
    type = "string"
  }

  property "Quantity" {
    required = true
    type = "int"
  }

  property "ActualCost" {
    required = true
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_UnitMeasure" {
  key = ["UnitMeasureCode"]

  property "UnitMeasureCode" {
    required = true
    type = "string"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_WorkOrder" {
  key = ["WorkOrderID"]

  property "WorkOrderID" {
    required = true
    type = "int"
  }

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "OrderQty" {
    required = true
    type = "int"
  }

  property "StockedQty" {
    type = "decimal"
  }

  property "ScrappedQty" {
    required = true
    type = "int"
  }

  property "StartDate" {
    required = true
    type = "string"
  }

  property "EndDate" {
    type = "string"
  }

  property "DueDate" {
    required = true
    type = "string"
  }

  property "ScrapReasonID" {
    entity = "Production_ScrapReason"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Production_WorkOrderRouting" {
  key = ["WorkOrderID","ProductID","OperationSequence"]

  property "WorkOrderID" {
    required = true
    entity = "Production_WorkOrder"
  }

  property "ProductID" {
    required = true
    type = "int"
  }

  property "OperationSequence" {
    required = true
    type = "int"
  }

  property "LocationID" {
    required = true
    entity = "Production_Location"
  }

  property "ScheduledStartDate" {
    required = true
    type = "string"
  }

  property "ScheduledEndDate" {
    required = true
    type = "string"
  }

  property "ActualStartDate" {
    type = "string"
  }

  property "ActualEndDate" {
    type = "string"
  }

  property "ActualResourceHrs" {
    type = "decimal"
  }

  property "PlannedCost" {
    required = true
    type = "decimal"
  }

  property "ActualCost" {
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Purchasing_ProductVendor" {
  key = ["ProductID","BusinessEntityID"]

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "BusinessEntityID" {
    required = true
    entity = "Purchasing_Vendor"
  }

  property "AverageLeadTime" {
    required = true
    type = "int"
  }

  property "StandardPrice" {
    required = true
    type = "decimal"
  }

  property "LastReceiptCost" {
    type = "decimal"
  }

  property "LastReceiptDate" {
    type = "string"
  }

  property "MinOrderQty" {
    required = true
    type = "int"
  }

  property "MaxOrderQty" {
    required = true
    type = "int"
  }

  property "OnOrderQty" {
    type = "int"
  }

  property "UnitMeasureCode" {
    required = true
    entity = "Production_UnitMeasure"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Purchasing_PurchaseOrderDetail" {
  key = ["PurchaseOrderID","PurchaseOrderDetailID"]

  property "PurchaseOrderID" {
    required = true
    entity = "Purchasing_PurchaseOrderHeader"
  }

  property "PurchaseOrderDetailID" {
    required = true
    type = "int"
  }

  property "DueDate" {
    required = true
    type = "string"
  }

  property "OrderQty" {
    required = true
    type = "int"
  }

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "UnitPrice" {
    required = true
    type = "decimal"
  }

  property "LineTotal" {
    type = "decimal"
  }

  property "ReceivedQty" {
    required = true
    type = "decimal"
  }

  property "RejectedQty" {
    required = true
    type = "decimal"
  }

  property "StockedQty" {
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Purchasing_PurchaseOrderHeader" {
  key = ["PurchaseOrderID"]

  property "PurchaseOrderID" {
    required = true
    type = "int"
  }

  property "RevisionNumber" {
    required = true
    type = "int"
  }

  property "Status" {
    required = true
    type = "int"
  }

  property "EmployeeID" {
    required = true
    entity = "HumanResources_Employee"
  }

  property "VendorID" {
    required = true
    entity = "Purchasing_Vendor"
  }

  property "ShipMethodID" {
    required = true
    entity = "Purchasing_ShipMethod"
  }

  property "OrderDate" {
    required = true
    type = "string"
  }

  property "ShipDate" {
    type = "string"
  }

  property "SubTotal" {
    required = true
    type = "decimal"
  }

  property "TaxAmt" {
    required = true
    type = "decimal"
  }

  property "Freight" {
    required = true
    type = "decimal"
  }

  property "TotalDue" {
    required = true
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Purchasing_ShipMethod" {
  key = ["ShipMethodID"]

  property "ShipMethodID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ShipBase" {
    required = true
    type = "decimal"
  }

  property "ShipRate" {
    required = true
    type = "decimal"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Purchasing_Vendor" {
  key = ["BusinessEntityID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_BusinessEntity"
  }

  property "AccountNumber" {
    required = true
    type = "string"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "CreditRating" {
    required = true
    type = "int"
  }

  property "PreferredVendorStatus" {
    required = true
    type = "int"
  }

  property "ActiveFlag" {
    required = true
    type = "int"
  }

  property "PurchasingWebServiceURL" {
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_CountryRegionCurrency" {
  key = ["CountryRegionCode","CurrencyCode"]

  property "CountryRegionCode" {
    required = true
    entity = "Person_CountryRegion"
  }

  property "CurrencyCode" {
    required = true
    entity = "Sales_Currency"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_CreditCard" {
  key = ["CreditCardID"]

  property "CreditCardID" {
    required = true
    type = "int"
  }

  property "CardType" {
    required = true
    type = "string"
  }

  property "CardNumber" {
    required = true
    type = "string"
  }

  property "ExpMonth" {
    required = true
    type = "int"
  }

  property "ExpYear" {
    required = true
    type = "int"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_Currency" {
  key = ["CurrencyCode"]

  property "CurrencyCode" {
    required = true
    type = "string"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_CurrencyRate" {
  key = ["CurrencyRateID"]

  property "CurrencyRateID" {
    required = true
    type = "int"
  }

  property "CurrencyRateDate" {
    required = true
    type = "string"
  }

  property "FromCurrencyCode" {
    required = true
    entity = "Sales_Currency"
  }

  property "ToCurrencyCode" {
    required = true
    entity = "Sales_Currency"
  }

  property "AverageRate" {
    required = true
    type = "decimal"
  }

  property "EndOfDayRate" {
    required = true
    type = "decimal"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_Customer" {
  key = ["CustomerID"]

  property "CustomerID" {
    required = true
    type = "int"
  }

  property "PersonID" {
    entity = "Person_Person"
  }

  property "StoreID" {
    entity = "Sales_Store"
  }

  property "TerritoryID" {
    entity = "Sales_SalesTerritory"
  }

  property "AccountNumber" {
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_PersonCreditCard" {
  key = ["BusinessEntityID","CreditCardID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_Person"
  }

  property "CreditCardID" {
    required = true
    entity = "Sales_CreditCard"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesOrderDetail" {
  key = ["SalesOrderID","SalesOrderDetailID"]

  property "SalesOrderID" {
    required = true
    entity = "Sales_SalesOrderHeader"
  }

  property "SalesOrderDetailID" {
    required = true
    type = "int"
  }

  property "CarrierTrackingNumber" {
    type = "string"
  }

  property "OrderQty" {
    required = true
    type = "int"
  }

  property "ProductID" {
    required = true
    entity = "Sales_SpecialOfferProduct"
  }

  property "SpecialOfferID" {
    required = true
    entity = "Sales_SpecialOfferProduct"
  }

  property "UnitPrice" {
    required = true
    type = "decimal"
  }

  property "UnitPriceDiscount" {
    required = true
    type = "decimal"
  }

  property "LineTotal" {
    type = "decimal"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesOrderHeader" {
  key = ["SalesOrderID"]

  property "SalesOrderID" {
    required = true
    type = "int"
  }

  property "RevisionNumber" {
    required = true
    type = "int"
  }

  property "OrderDate" {
    required = true
    type = "string"
  }

  property "DueDate" {
    required = true
    type = "string"
  }

  property "ShipDate" {
    type = "string"
  }

  property "Status" {
    required = true
    type = "int"
  }

  property "OnlineOrderFlag" {
    required = true
    type = "int"
  }

  property "SalesOrderNumber" {
    type = "string"
  }

  property "PurchaseOrderNumber" {
    type = "string"
  }

  property "AccountNumber" {
    type = "string"
  }

  property "CustomerID" {
    required = true
    entity = "Sales_Customer"
  }

  property "SalesPersonID" {
    entity = "Sales_SalesPerson"
  }

  property "TerritoryID" {
    entity = "Sales_SalesTerritory"
  }

  property "BillToAddressID" {
    required = true
    entity = "Person_Address"
  }

  property "ShipToAddressID" {
    required = true
    entity = "Person_Address"
  }

  property "ShipMethodID" {
    required = true
    entity = "Purchasing_ShipMethod"
  }

  property "CreditCardID" {
    entity = "Sales_CreditCard"
  }

  property "CreditCardApprovalCode" {
    type = "string"
  }

  property "CurrencyRateID" {
    entity = "Sales_CurrencyRate"
  }

  property "SubTotal" {
    required = true
    type = "decimal"
  }

  property "TaxAmt" {
    required = true
    type = "decimal"
  }

  property "Freight" {
    required = true
    type = "decimal"
  }

  property "TotalDue" {
    type = "decimal"
  }

  property "Comment" {
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesOrderHeaderSalesReason" {
  key = ["SalesOrderID","SalesReasonID"]

  property "SalesOrderID" {
    required = true
    entity = "Sales_SalesOrderHeader"
  }

  property "SalesReasonID" {
    required = true
    entity = "Sales_SalesReason"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesPerson" {
  key = ["BusinessEntityID"]

  property "BusinessEntityID" {
    required = true
    entity = "HumanResources_Employee"
  }

  property "TerritoryID" {
    entity = "Sales_SalesTerritory"
  }

  property "SalesQuota" {
    type = "decimal"
  }

  property "Bonus" {
    required = true
    type = "decimal"
  }

  property "CommissionPct" {
    required = true
    type = "decimal"
  }

  property "SalesYTD" {
    required = true
    type = "decimal"
  }

  property "SalesLastYear" {
    required = true
    type = "decimal"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesPersonQuotaHistory" {
  key = ["BusinessEntityID","QuotaDate"]

  property "BusinessEntityID" {
    required = true
    entity = "Sales_SalesPerson"
  }

  property "QuotaDate" {
    required = true
    type = "string"
  }

  property "SalesQuota" {
    required = true
    type = "decimal"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesReason" {
  key = ["SalesReasonID"]

  property "SalesReasonID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "ReasonType" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesTaxRate" {
  key = ["SalesTaxRateID"]

  property "SalesTaxRateID" {
    required = true
    type = "int"
  }

  property "StateProvinceID" {
    required = true
    entity = "Person_StateProvince"
  }

  property "TaxType" {
    required = true
    type = "int"
  }

  property "TaxRate" {
    required = true
    type = "decimal"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesTerritory" {
  key = ["TerritoryID"]

  property "TerritoryID" {
    required = true
    type = "int"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "CountryRegionCode" {
    required = true
    entity = "Person_CountryRegion"
  }

  property "Group" {
    required = true
    type = "string"
  }

  property "SalesYTD" {
    required = true
    type = "decimal"
  }

  property "SalesLastYear" {
    required = true
    type = "decimal"
  }

  property "CostYTD" {
    required = true
    type = "decimal"
  }

  property "CostLastYear" {
    required = true
    type = "decimal"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SalesTerritoryHistory" {
  key = ["BusinessEntityID","StartDate","TerritoryID"]

  property "BusinessEntityID" {
    required = true
    entity = "Sales_SalesPerson"
  }

  property "TerritoryID" {
    required = true
    entity = "Sales_SalesTerritory"
  }

  property "StartDate" {
    required = true
    type = "string"
  }

  property "EndDate" {
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_ShoppingCartItem" {
  key = ["ShoppingCartItemID"]

  property "ShoppingCartItemID" {
    required = true
    type = "int"
  }

  property "ShoppingCartID" {
    required = true
    type = "string"
  }

  property "Quantity" {
    required = true
    type = "int"
  }

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "DateCreated" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SpecialOffer" {
  key = ["SpecialOfferID"]

  property "SpecialOfferID" {
    required = true
    type = "int"
  }

  property "Description" {
    required = true
    type = "string"
  }

  property "DiscountPct" {
    required = true
    type = "decimal"
  }

  property "Type" {
    required = true
    type = "string"
  }

  property "Category" {
    required = true
    type = "string"
  }

  property "StartDate" {
    required = true
    type = "string"
  }

  property "EndDate" {
    required = true
    type = "string"
  }

  property "MinQty" {
    required = true
    type = "int"
  }

  property "MaxQty" {
    type = "int"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_SpecialOfferProduct" {
  key = ["SpecialOfferID","ProductID"]

  property "SpecialOfferID" {
    required = true
    entity = "Sales_SpecialOffer"
  }

  property "ProductID" {
    required = true
    entity = "Production_Product"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "Sales_Store" {
  key = ["BusinessEntityID"]

  property "BusinessEntityID" {
    required = true
    entity = "Person_BusinessEntity"
  }

  property "Name" {
    required = true
    type = "string"
  }

  property "SalesPersonID" {
    entity = "Sales_SalesPerson"
  }

  property "Demographics" {
    type = "string"
  }

  property "rowguid" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "dbo_AWBuildVersion" {
  key = ["SystemInformationID"]

  property "SystemInformationID" {
    required = true
    type = "int"
  }

  property "Database_Version" {
    required = true
    type = "string"
  }

  property "VersionDate" {
    required = true
    type = "string"
  }

  property "ModifiedDate" {
    required = true
    type = "string"
  }
}

entity "dbo_DatabaseLog" {
  key = ["DatabaseLogID"]

  property "DatabaseLogID" {
    required = true
    type = "int"
  }

  property "PostTime" {
    required = true
    type = "string"
  }

  property "DatabaseUser" {
    required = true
    type = "string"
  }

  property "Event" {
    required = true
    type = "string"
  }

  property "Schema" {
    type = "string"
  }

  property "Object" {
    type = "string"
  }

  property "TSQL" {
    required = true
    type = "string"
  }

  property "XmlEvent" {
    required = true
    type = "string"
  }
}

entity "dbo_ErrorLog" {
  key = ["ErrorLogID"]

  property "ErrorLogID" {
    required = true
    type = "int"
  }

  property "ErrorTime" {
    required = true
    type = "string"
  }

  property "UserName" {
    required = true
    type = "string"
  }

  property "ErrorNumber" {
    required = true
    type = "int"
  }

  property "ErrorSeverity" {
    type = "int"
  }

  property "ErrorState" {
    type = "int"
  }

  property "ErrorProcedure" {
    type = "string"
  }

  property "ErrorLine" {
    type = "int"
  }

  property "ErrorMessage" {
    required = true
    type = "string"
  }
}
